spring:
  rabbitmq:
    host: 10.200.44.212
    username: lmk
    password: lmk
    virtual-host: test
mqtt:
  clientId: rabbitmq-client
  username: admin
  password: public
  host: tcp://127.0.0.1:1883
  will-topic: rabbitmq-client-will
  will-qos: 0